### ISSUE TITLE
Suggestion to remove tabs on input

### ISSUE THREAD

**Issue by gt9000** [glotlabs/seedphrase#1]
I love your tool - I have been cutting and pasting from Excel and found removing the tabs tedious. Not a Rust developer, but I made this change running locally now with no issues. 

            Msg::MnemonicChanged(captured) => {
                model.mnemonic = captured.value().replace("\t", " ");
                Ok(vec![])
            }

**Comment by prasmussen** [comment]
This is great, will incorporate shortly.
I'm impressed that you were able to get this running locally :)

**Comment by prasmussen** [comment]
Change is pushed

**Comment by gt9000** [comment]
LOL, yeah, wasn't particularly easy - but fun figuring it out. Now if I can only figure out Decoherence! 

Thank you for making the change!

**Comment by prasmussen** [comment]
Haha, I've used countless hours on Decoherence and more or less given up.
I hope someone solves it soon so that I can get some closure.
Good luck!

**Comment by gt9000** [comment]
Yeah, I keep playing around with it. Obsession has gone, but can't really let go. lol
Agreed.
Thank you!
